language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8"
  - "3.8-dev" # 3.7 development branch
env:
  - GEVENT=true
  - GEVENT=false

install:
  - pip install gevent\<1.5.0 pytest-random-order
  # PyYaml 5.3 removed support for Python 3.4
  - |-
    if [[ $TRAVIS_PYTHON_VERSION = 3.4 ]]; then
      pip install PyYaml==5.2
    else
      pip install PyYaml
    fi
  - pip install sphinx==1.7.9 ghp-import

before_script:
  # we need this for test_ziplog, which parses ambiguous timestamps
  - export TZ=Asia/Jerusalem

script:
  - python -m pytest --random-order-bucket=package -vv test_package.py  # separate, since it mucks with imports
  - python -m pytest --random-order-bucket=package -vv tests
  - python -m pytest --random-order-bucket=package -vv --doctest-modules easypy

notifications:
    email:
        on_success: change
        on_failure: change

after_success: |-
  [[ $TRAVIS_JOB_NUMBER = *.1 ]] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  sphinx-apidoc -o _static easypy &&
  PYTHONPATH=`pwd`:$PYTHONPATH sphinx-build -M html "." "_build" &&
  echo "<meta http-equiv=refresh content=0;url=html/_static/easypy.html>" > _build/index.html &&
  export PATH=$HOME/.local/bin:$PATH &&
  ghp-import -n _build &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
deploy:
  provider: pypi
  user: __token__
  password:
    secure: NhavGu3sOaDgBH8QWhui6qDI/XMR8hLbiiruvXYmE/UUlnZvzmWVMURerFQjudo0Wbn8Yzh9PazoAS+c6xdzzFZo9PBWwTZo4QsPYaVgTfrIfFKkZDKXrm63BM71QkRFExG0g4iARBENiKoHkwt4b+nOmSMYRjH8wNs7TzsZK86f51Ky1Yai1XtMtF2f5kHMK7jQXako8+G/zPnAJhgxWr5vz0mLEAEis+dLeTsvw//1yEAm9FbCGt1xFBu0kYO4OelwUTemNVvjNi6ly9PuqI/sAR3R6yBP4E00gh1Al6HdKNmsuj4t8Z8dFaheN8fS+/QVfDpxjqd37U0EG3xlEdXbuXiMgR7fz+LqgLHdbxysH8D6JDiFjbZ+NH9q+jUZr75dGpZd0+UrVjmbV8XKFfML/murBGoxz+Jen/Owhbjcba7KUihuIjxBle9gHLq/iZM6Y65U277SpIuPXDQHqJ0+ZiINa8O5CcNxcDKBkgz12QjpFM1uEpnwbNeYop3cpgisjo9sYJJyTYvE6yPwu7JtG6NaaBLuJnd8sUPtpe9OCNFE+VQ5ETdFT9a3D3Y5i8fXGrzaVOIz+k+A3Q3BLwjdMJitWAu7HhOOMn3UTSsjaBZkdroU3g9Zrb5B/drSzk+yrZpl63D7mQdHc00agnWBwCQ36WDMU9a1Cyx15F8=
  on:
    tags: true
  skip_existing: true
